platform:
    - x86
    - x64

environment:
    matrix:
        - VSVER: 14

before_build:
    - ps: >-
        If ($env:Platform -Match "x86") {
            $env:VCVARS_PLATFORM="x86"
            $env:TARGET="VC-WIN32"
        } Else {
            $env:VCVARS_PLATFORM="amd64"
            $env:TARGET="VC-WIN64A"
        }
    - call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" %VCVARS_PLATFORM%

build_script:
    - cd tests_catch/
    - cmake -G "NMake Makefiles" && nmake
    - nmake install
